### ISSUE TITLE
We don't allow benchmarking only one package

### ISSUE THREAD

**Issue by Razican** [boa-dev/criterion-compare-action#5]
In [this commit][commit], we removed the `-p Boa` from the command. This makes it portable for other things, but it removes the posibility to benchmark a certain package in a workspace.

This is causing all boa builds to fail. We should include an optional "package" parameter in the action configuration, and add it to the command line arguments.

[commit]: https://github.com/boa-dev/criterion-compare-action/commit/2aba55cc78a7c7f8d29c9ba8e083e3766c53aaa8

**Comment by Razican** [comment]
This has been solved by `cwd`, but we should probably still allow using the `-p` benchmarking option.

**Comment by HalidOdat** [comment]
Should be fixed in #91
